### ISSUE TITLE
能否先打开zlrc，然后把mp3文件拖放上去？

### ISSUE THREAD

**Issue by liuzhaoyzz** [emako/zlrc#1]
能否先打开zlrc，然后把mp3文件拖放上去？这样子zlrc可以放在任何地方，不需要每次放在同一个目录下拖放不方便，歌曲太多的时候，拖放也不方便。

**Comment by emako** [comment]
现在zlrc就可以放在任何地方，打开2个目录就可以了。

**Comment by emako** [comment]
![动画](https://github.com/user-attachments/assets/893c0b5f-6ccc-4104-b9b2-9997de57dacc)
